export const actionsType = {
  COUNTER_INC: 'COUNTER_INC',
  COUNTER_DEC: 'COUNTER_DEC',
  COUNTER_RES: 'COUNTER_RES',
  STEP_NEXT: 'STEP_NEXT',
  STEP_PREV: 'STEP_PREV',
  SET_SMOKING_DATA: 'SET_SMOKING_DATA',
  SET_AUTH: 'SET_AUTH',
};
